### ISSUE TITLE
Is there a way to calculate incremental code coverage

### ISSUE THREAD

**Issue by Alan-huan** [linux-test-project/lcov#157] opened 2022-06-15 03:18 UTC
Is there a way to calculate incremental code coverage

**Comment by henry2cox** [comment] 2022-06-15 10:47
Depending on what you mean by “incremental code coverage”:  yes.

See the discussion about differential coverage in PR #86..

I also wrote a small application to prune tests based on ‘effectiveness’ (whether they cover previously unexercised code, or contain previously unseen code) – but have not merged that yet.
(Obviously, the problem is NP-hard and the approach I took is greedy/not optimal.)

Hope that helps.

Henry

**Comment by henry2cox** [comment] 2022-11-30 12:46
Following up from quite long back:
The differential approach mentioned in the PR #86 has been merged to master.
If I understand what you meant by 'incremental coverage' then you can try the following steps to see if that meets your requirement:

1. build your code 
2. run test suite A; run 'lcov --capture -o baseline.info ...' to extract coverage from suite A
3. run test suite B:  run 'lcov --capture -o incremental.info ...' to extract cumulative coverage from A and B
If you want just the coverage from B (i.e., not cumulative), then remove all the .gcda files in your sandbox before you run the second set of tests
4. run 'genhtml -o difference --baseline-file baseline.info current.info 
Open browser to ..../difference/index.html.
Code that was covered in B but not in A will be categorized as "GBC" in the table.  Code covered in both will be categorized as "CBC".  Code that is not covered in either will be "UBC".  (See the referred paper for a description of categories and why you care.)
If you generated an info file for B alone (i.e., not cumulative for both A and B) - then code that is covered in A and not covered in B will fall into the "LBC" category.
The above assumes that you did not change code between A and B.
If you _did_ modify your implementation, then you also need to tell genhtml what changed.  See the man page for "--annotate-script" and/or look at the testcases.
If this meets your requirement:  please close this issue.
If there is something else that can be done...please describe and I will try to implement it.  I guarantee that any feature that you would find interesting/useful is a feature that everyone else will also want to have ... if only they knew what it was.
I hope that helps.
Henry

**Comment by henry2cox** [comment] 2023-05-11 13:31
No followup on this issue from anyone except me since it was opened.
I believe that the issue is resolved - though possibly not how @Alan-huan was expecting.
Thus:  I will close the issue now.

If there is still a problem, please reopen the issue or file a new one.  Please include a detailed description of the problem - including a testcase and/or mocked up screen shots of what you want to see.

I am trying to clean up the issue list to make it easier to find problems that still need to be addressed.
Henry

**Closed by henry2cox** 2023-05-11 13:31 UTC
