### ISSUE TITLE
LCOV is generating coverage reports for only header files

### ISSUE THREAD

**Issue by asen3** [linux-test-project/lcov#65] opened 2019-04-25 16:58 UTC
I am using lcov and genhtml to generate code coverage reports. My unit test files only include the .h header files.

client_test.cpp
```
#include "gtest/gtest.h"
#include "../client.h"
...
```
```
lcov --capture --no-external --rc lcov_branch_coverage=1 --directory . --output-file unfiltered_coverage.info
```
I have noticed that the coverage report only contains coverage information for the files which were in the include section of my unit tests. Thus, the coverage report only contains the client.h file and not the client.cpp file.

**Comment by latk** [comment] 2019-04-26 08:41
Did you compile the `client.cpp` file with coverage options as well? In order to collect coverage, the compiler must instrument the binary with extra counters. Headers are just compiled into other object files, they are not compiled by themselves. Here it seems you see the headers because the compiler instrumented the object code for the test code, which includes the headers.

**Comment by asen3** [comment] 2019-04-26 14:17
Yes, I compile the .cpp file with the --coverage option.

**Comment by oberpar** [comment] 2020-08-04 08:31
I can reproduce the problem with a source tree like this:
```
src/client.h
src/subdir/client_test.cpp
```
When lcov is run inside `src/subdir` with both `--directory .` and `--no-external`, lcov filters out `src/client.h` since it is outside of the directory specified by `--directory`. This is working as designed. See also the `lcov` man description of `--no-external`:
```
       --no-external
              Specify  whether  to  capture  coverage data for external source
              files.

              External source files are files which are not located in one  of
              the  directories  specified  by --directory or --base-directory.
              Use --external to include external source files while  capturing
              coverage data or --no-external to ignore this data.
```
To fix this problem, specify the top level source directory with lcov's '--directory' option (`src/` in this example).

I'm closing this issue since this works as designed. Please re-open if the problem persists with the described workaround.

**Closed by oberpar** 2020-08-04 08:31 UTC
