### ISSUE TITLE
Can't open perl script "/c/dev/mylib/build/geninfo": No such file or directory

### ISSUE THREAD

**Issue by bartekleon** [linux-test-project/lcov#112] opened 2021-01-06 20:48 UTC
It is a strictly windows problem that even tho cmake finds all lcov, gcov, geninfo etc. coverage fails because of this strange path, so I want to ask if there is an option to set this path for lcov like :
```
FIND_PROGRAM( GENINFO_PATH geninfo )
lcov --geninfo-path ${GENINFO_PATH} --directory . --base-directory . --capture --output-file coverage.info
```
?
It would be very nice to have it working for linux and windows - and I believe it is the last step to make it possible - unless it is possible and it is just that i cannot find options to do so

**Comment by henry2cox** [comment] 2023-01-06 15:55
generally, 'lcov' and 'geninfo' are in the same bin directory...so your shell should be able to find geninfo if it found lcov.

If the issue is 'gcov' (or 'llvm-cov') then yes.  See the man page for the "--gcov-tool" option.

If this answers your question:  please close this issue.
If some problems remain:  please describe them.
Thanks
Henry

**Comment by henry2cox** [comment] 2023-05-11 13:49
There have been no updates in a very long time.
Is this still a problem?
If so:  please describe your environment and include a testcase that exhibits the issue.

If no updates in a week or two:  I will assume that the problem has been addressed and will close this issue.

Henry

**Comment by henry2cox** [comment] 2023-05-15 16:34
Following up on my own comment:
Yes, pretty sure this issue still exists on windows with current TOT code.
The issue has to do with lack of support for "#! ..." scripts in windows.

**Comment by henry2cox** [comment] 2023-05-16 10:21
I think that the specific issue of the `#!` in the geninfo script is fixed in https://github.com/linux-test-project/lcov/commit/398fa7ead0eaffe8e33461f99c4168b4585489f5 - however, there may be other issues that prevent the tools from working correctly on windows.

**Comment by henry2cox** [comment] 2023-05-22 11:36
No responses/no updates - so I assume that this issue has been addressed.

If there is still a problem, please either reopen this issue or file a new one.
Please include a detailed description of the problem, and ideally include a testcase which exhibits the issue.
Henry

**Closed by henry2cox** 2023-05-22 11:36 UTC
