### ISSUE TITLE
static function is not included in the coverage.

### ISSUE THREAD

**Issue by yangsee0** [linux-test-project/lcov#273] opened 2024-03-07 00:31 UTC
Hello.
i called the static function, but it is not included in the coverage.
if static is removed, it is included in coverage.
There are several static functions in the same file, but only this function is not included.
What's the cause?
I would appreciate it if you could tell me how to solve it.
Thank you.

ex)
0: static void A(int a) {          
0:          xxx = malloc(x);
  : }

10: static void B(int b) {
10:             A(a);
    :}

rhel8.8
lcov 2.0

**Comment by henry2cox** [comment] 2024-03-07 10:44
More information would be helpful

- compiler version
- compiler command line, link command line
- lcov command line
- complete, compile and runnable example that illustrates the issue.

From your description, I am guessing that your lcov version is the 2.0 release - not a copy of top-of-tree from this repo.
If this is true:  can you try your example again with TOT, and see if it still misbehaves.

Thanke

**Comment by henry2cox** [comment] 2024-03-15 12:17
Closing this now.
Unable to reproduce.  Existing examples all work as expected.

If there is still a problem, please either reopen this issue or file a new one.
Please include a testcase which illustrates the bug as well as directions (including environment, tool versions, etc) required to reproduce.

**Closed by henry2cox** 2024-03-15 12:17 UTC
