### ISSUE TITLE
lcov incompatible with GCC 9.x  coverage data

### ISSUE THREAD

**Issue by berrange** [linux-test-project/lcov#58] opened 2019-01-24 13:09 UTC
Fedora 30 rawhide has pulled in the last GCC 9.0.0 version and this appears incompatible with lcov

```
$ echo "const int a = 5; int main(void) { return 1;}" > t.c
$ gcc -Wall -Wextra -Werror ./t.c --coverage
$ ./a.out 
```

Previously with GCC 8 compiled binaries this would work:

```
$ lcov -t "result" -o ex_test.info -c -d .
Capturing coverage data from .
Found gcov version: 8.2.1
Scanning . for .gcda files ...
Found 1 data files in .
Processing t.gcda
Finished .info-file creation
$ lcov -l ex_test.info
Reading tracefile ex_test.info
            |Lines       |Functions  |Branches    
Filename    |Rate     Num|Rate    Num|Rate     Num
==================================================
[/home/berrange/src/virt/libvirt-go/]
t.c         | 100%      1| 100%     1|    -      0
==================================================
      Total:| 100%      1| 100%     1|    -      0
```

With GCC 9 compiled binaries it fails

```
$ ./lcov/bin/lcov -t "result" -o ex_test.info -c -d .
Capturing coverage data from .
Found gcov version: 9.0.0
Scanning . for .gcda files ...
Found 1 data files in .
Processing t.gcda
geninfo: WARNING: /home/berrange/t.gcno: Overlong record at end of file!
geninfo: WARNING: gcov did not create any files for /home/berrange/t.gcda!
Finished .info-file creation
```

There are some GCC changes that affected coverage data format:

https://gcc.gnu.org/viewcvs/gcc?view=revision&revision=261189
https://gcc.gnu.org/viewcvs/gcc?view=revision&revision=264462

The info above is all taken from a Fedora bug report https://bugzilla.redhat.com/show_bug.cgi?id=1668843

**Comment by robinmoussu** [comment] 2019-01-26 19:48
In case it may help, on my [pet project](https://gitlab.com/robinmoussu/rollordie3) I can use gcov to get the code coverage, but lcov fails. A really recent g++9 build is required, some stuff were fixed in gcov less than a week go and it uses C++20 feature only available on g++ at the moment. 

if you have meson + conan + lcov + genhtml installed, and an extremely fresh build of g++9, it should be as easy to test as

```
git clone https://gitlab.com/robinmoussu/rollordie3.git && cd rollordie3
make
make coverage
```

I didn't tested to install it from another computer than mine however.

Feel free to ask me any additional data.

**Comment by oberpar** [comment] 2019-03-01 16:38
I can confirm that the problem exists with LCOV and GCC 9.0 .gcno files. This will be addressed via the LCOV intermediate file format support that I'm working on.

**Comment by marxin** [comment] 2019-03-08 13:36
> I can confirm that the problem exists with LCOV and GCC 9.0 .gcno files. This will be addressed via the LCOV intermediate file format support that I'm working on.

Great, may I ignore this as the intermediate support in LCOV will appear before GCC 9.1 is released (May 2019) ?

**Comment by oberpar** [comment] 2019-03-08 14:57
LCOV support for the intermediate file format will (hopefully) be available before May.

**Comment by oxr463** [comment] 2019-05-09 14:37
In my tests, I can confirm this issue affects the following versions:

- 9.1,  (See: https://gitlab.com/proot/proot/-/jobs/199163599).
- 8.3, (See: https://gitlab.com/proot/proot/-/jobs/209815447).

Tested on official docker images, (See: https://hub.docker.com/_/gcc), for each version, respectfully.

@oberpar are there any issues blocking this that require assistance?

**Comment by oberpar** [comment] 2019-05-28 15:43
This should be fixed with commit 75fbae1cfc5027f818a0bb865bf6f96fab3202da.

**Comment by LesnyRumcajs** [comment] 2019-06-24 13:49
I can confirm, this is working fine with `gcc-9.1.1` minus the extra dependencies I had to install manually.

**Comment by rockdaboot** [comment] 2019-08-16 14:59
Do you already plan a new release ? Debian (unstable) just switched to gcc 9.2.1 ... :-)

**Comment by oberpar** [comment] 2019-08-20 11:15
Currently no new release is planned. LCOV GCC 9 support for Debian should be covered by a package upgrade to 1.14-2. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=924573

**Comment by rockdaboot** [comment] 2019-08-20 12:51
That bug has been opened in March. I left a comment about gcc 9 on Friday - Saturday they had it fixed :-)

**Comment by marxin** [comment] 2019-08-23 08:01
openSUSE Tumbleweed also offers the package that includes the patch:

```
https://software.opensuse.org/package/lcov?search_term=lcov
lcov-1.15+git.20190524.75fbae1.tar.xz
```

**Comment by bayandin** [comment] 2020-02-12 19:39
Hello, is there any plans for the next release with gcc-9 support?

**Comment by Apteryks** [comment] 2020-05-09 04:05
> Hello, is there any plans for the next release with gcc-9 support?

I too would like to see a new release; at least a tag in here. The only thing missing seems to list the additional new dependencies in the installation section of the README.

**Comment by sarangjo** [comment] 2020-07-27 19:59
Can this be closed and replaced with a separate request to publish a release? `master` works well with GCC 9.3.0 per my testing

**Comment by lipnitsk** [comment] 2020-07-28 22:09
@oberpar given how stable this project is (few changes in the last year) and the amount of exposure this issue has received in various distros (I use Arch), isn't it time to tag a new release?

**Comment by oberpar** [comment] 2020-08-04 14:20
I'm currently reviewing the remaining open issues and pull requests for anything that should be included in the next release. Once I'm done with that I plan to release LCOV 1.15 (should be sometime next week).

**Comment by oberpar** [comment] 2020-08-04 14:59
Closing this issue since the original problem has been addressed.

**Closed by oberpar** 2020-08-04 14:59 UTC
