### ISSUE TITLE
genhtml warning use of uninitialized value 

### ISSUE THREAD

**Issue by icsfy** [linux-test-project/lcov#268] opened 2024-02-06 11:55 UTC
lcov latest git version

genhtml: WARNING: Use of uninitialized value in numeric ne (!=) at bin/genhtml line 1036.

**Comment by henry2cox** [comment] 2024-02-06 11:59
Testcase?

**Comment by henry2cox** [comment] 2024-02-06 12:16
My code looks a bit different than what you currently have...
Could you change the code near your like 1036, to look like:

`  if ($lineData->in_curr()) {`
`      $l->{hit} -= $lineData->curr_count() != 0;`
`       $l->{found} -= 1;`
`  }`

That may make the issue go away.
(Sorry about that.)

**Comment by henry2cox** [comment] 2024-02-06 13:07
Ah - good.
I will push the fix sometime later this week, or possibly next.

**Comment by henry2cox** [comment] 2024-02-07 17:43
Should be fixed in e3f73953c.
If the issue is fixed: please go ahead and close it - otherwise, I probably need a testcase.

**Closed** 2024-02-16 15:15 UTC
