### ISSUE TITLE
use of system specific system calls like pwd and /dev/null break native Win32 support

### ISSUE THREAD

**Issue by GitMensch** [linux-test-project/lcov#215] opened 2023-05-11 15:02 UTC
Some commands use `pwd`: https://github.com/search?q=repo%3Alinux-test-project%2Flcov+pwd+language%3APerl&type=code&l=Perl and redirection to `/dev/null`: https://github.com/search?q=repo%3Alinux-test-project%2Flcov+dev%2Fnull+language%3APerl&type=code&l=Perl

Please replace the system specific calls to perl functions where possible - like `getwcd()` and have the redirection adjusted to `File::Spec->devnull();`.
Both can be seen in the outdated https://github.com/linux-test-project/lcov/pull/155/files.

Also the invocation of perl subscripts should use the current interpreter - that's something done conditional to Win32 in https://github.com/linux-test-project/lcov/pull/74/commits/62f26f8e50066c46b64311ea708a8701e41092be - but I think it is reasonable to always do that.

I don't want to do those a third time... and as it seems to be quite "small" change I hope someone can implement this to the current version removing the need for (too much) patching 2.0 again.

**Comment by GitMensch** [comment] 2023-05-11 16:00
Actually: if you could tackle that and make those adjustments "prefer Perl instead of native" and test those on GNU/Linux, then this would already be beneficial (switching to system commands is always an overhead and less portable than using perl).

**Comment by GitMensch** [comment] 2023-05-15 19:14
That looks promising. I'll report back if/when I'm doing the MSYS2 update to upcoming 2.0.

**Comment by GitMensch** [comment] 2023-05-26 10:51
@henry2cox I assume 9113a1f4ecb13408df41e62a5c5103df798d78c7 should take care about some issues? Should I try the MSYS2 packaging with using 2.0 plus https://github.com/linux-test-project/lcov/commit/9113a1f4ecb13408df41e62a5c5103df798d78c7.patch?

**Comment by henry2cox** [comment] 2023-05-26 11:37
Yes.
That is:  I had checked in a bunch of other fixes a few weeks ago - and those are in the 2.0 release tarball.
But I had noticed a few others later - and we decided that it was too risky/too potentially destabilizing to jam them into the release.  Better to make the release with code we knew works on linux...and worry about windows later.
Adding weight to the decision:  I'm pretty sure that windows will require more fixes - so there was really no point to add risk when we were pretty sure that we would not have a functional windows version either way.

**Comment by henry2cox** [comment] 2024-08-05 17:23
I'm going to go ahead and close this issue now - not because I believe that the current TOT will run correctly on windows, but because there have been a lot of changes to the code since this issue was created, but no updates or indication what of what is wrong/broken.

If there are still problems on windows (and I highly, highly suspect that there are) - please feel free to reopen this issue or file a new one.  Please include some details about what is wrong and/or a fairly detailed recipe for how to reproduce the problems.
Thanks
Henry

**Closed** 2024-08-05 17:33 UTC
