### ISSUE TITLE
Lcov process coverage report too slow with gcc9.

### ISSUE THREAD

**Issue by Shylock-Hg** [linux-test-project/lcov#78] opened 2020-03-20 02:19 UTC
I try to collect coverage with lcov 40580cd65909bc8324ae09b36bca2e178652ff3f, but it process too slow unusually than the lcov before gcc9.

**Comment by sdarwin** [comment] 2021-06-08 19:13
lcov 1.15 with gcov-10 seems to be _extremely slow_ compared to lcov 1.14 and gcc-6.

**Comment by xaizek** [comment] 2021-06-08 20:50
I think it will work faster if you set `geninfo_intermediate` variable to `0` in `lcovrc` or via `--rc` option. The problem must be caused by `lcov` invoking `gcov` for each input file separately instead of batching them (which should be done carefully because of [this bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=89961)).

**Comment by sfc-gh-sgiesecke** [comment] 2022-01-14 09:11
> I think it will work faster if you set geninfo_intermediate variable to 0

AFAIU, this isn't an option with gcc9+, given the explanation of https://github.com/linux-test-project/lcov/commit/75fbae1cfc5027f818a0bb865bf6f96fab3202da:
```
Note: The way that the intermediate file format support is implemented
in geninfo removes the need to parse .gcno files directly. Since geninfo
does not include support for parsing GCC 9 .gcno files, using the
intermediate format is the only option for geninfo to collect coverage
data generated by GCC version 9.
```

Or has support for parsing GCC 9 .gcno been added in the meantime?

**Comment by xaizek** [comment] 2022-01-14 21:40
> Or has support for parsing GCC 9 .gcno been added in the meantime?

Probably not. I didn't realize gcno format isn't parsed for newer versions of GCC. Thanks for the correction.

Not sure if this is actually doable, but maybe one could invoke gcov prior to lcov and then specify custom gcov command for lcov which will just reuse that output of gcov. Might not be worth it because some processing is necessary anyway (for running gcov multiple times and for picking which files to return to not miss any). GCC 9 is the first version which adds `--stdout` option, so it might be easier to use it and do not deal with files at all (which is both faster and avoids bugs mentioned above).

**Comment by henry2cox** [comment] 2023-01-06 15:46
Is this still an issue?
Could you re-try with current TOT, possibly try the "--parallel" flag as well  (see the man pages).
If you are more-or-less happy at that point:  please close this issue.
If not happy:  please include some statistics - and hopefully a testcase - so we can see if anything can be done to go faster.
Thanks
Henry

**Closed** 2023-01-10 02:05 UTC
