### ISSUE TITLE
Function definition in macro => mismatched end line

### ISSUE THREAD

**Issue by alkino** [linux-test-project/lcov#192] opened 2023-02-15 07:20 UTC
With this simple sample:
```c++
#define FOO void bar() {}; void foo() 

FOO {
}

int main() {
    return 0;
}
```

And this compilation line:
```sh
g++ -coverage main.cpp && lcov --initial --capture  --directory . --output-file coverage-base.info
```

I got this error:
```
Capturing coverage data from .
geninfo cmd: '/usr/bin/geninfo . --output-filename coverage-base.info --initial --parallel 1 --memory 0'
Found gcov version: 12.2.1
Using intermediate gcov format
Writing temporary data to /tmp/geninfo_datGRDd
Scanning . for .gcno files ...
Found 2 graph files in .
Processing ./foo-main.gcno
Processing ./a-main.gcno
geninfo: Error: mismatched end line for _Z3barv at /home/alkino/TEST/main.cpp:3: 4 -> 3
	(use "geninfo --ignore-errors mismatch ..." to bypass this error)
geninfo: cannot remove path when cwd is /tmp/geninfo_datGRDd/geninfo_Z6iKx for /tmp/geninfo_datGRDd/geninfo_Z6iKx:  at /usr/share/perl5/core_perl/File/Temp.pm line 2643.
geninfo: cannot remove path when cwd is /tmp/geninfo_datGRDd/geninfo_Z6iKx for /tmp/geninfo_datGRDd:  at /usr/share/perl5/core_perl/File/Temp.pm line 2643.
```

I think there is 2 errors here.

**Comment by henry2cox** [comment] 2023-02-15 12:01
I think the issue is fixed in  8664793b659c.

Note that gcov is generating some inconsistent data in this case (end line for function).
That causes geninfo to report an error - and then the 'die' related to that message collides with tempdir removal/cleanup by File::Temp.
I modified the code to avoid that collision - but the inconsistent data (and message) remain.
You can ignore the message and continue to generate the coverage data if you like ("lcov --capture --initial --ignore mismatch ...")

More generally:  gcc/gcov are not completely happy with macros and strangely formatted code :-(
There appears to be a pretty deeply held assumption that the body of a function will be on contiguous lines, between the start and end of the function definition.
All hell breaks out (...and we get inconsistent data from gcov) if that is not the case.  (Say - use "#include body.cpp" to suck in some or all of the function body - and observe some strange effects.)
(Mostly, I try to ask users to not write code that way.  They do not always listen.)

Thanks for finding (and reporting) the issues.
And sorry that you are finding issues...
Henry

**Comment by alkino** [comment] 2023-02-15 13:19
Yes with `--ignore mismatch` and the new patch it seems to work.

**Closed** 2023-02-15 14:15 UTC

**Comment by twied** [comment] 2023-10-15 10:42
gtest uses this kind of macro:

```cpp
// demo.cpp
#include <gtest/gtest.h>

TEST(Demo, Foobar) {
    EXPECT_EQ(1, 1);
}

int main(int argc, char* argv[]) {
    testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
```

```sh
$ g++ -coverage demo.cpp $(pkg-config --libs --cflags gtest) 
$ lcov --initial --capture --directory . --output-file demo.info
Capturing coverage data from .
geninfo cmd: '/usr/bin/geninfo . --output-filename demo.info --initial --memory 0'
Found gcov version: 13.2.0
Using intermediate gcov format
Writing temporary data to /tmp/geninfo_dats4WY
Scanning . for .gcno files ...
Found 1 graph files in .
Processing ./a-demo.gcno
geninfo: ERROR: mismatched end line for _ZN16Demo_Foobar_Test8TestBodyEv at (...)/demo.cpp:3: 3 -> 5
	(use "geninfo --ignore-errors mismatch ..." to bypass this error)

```

Adding `--ignore mismatch` is not an option when using e.g. meson as build system:

```meson
# meson.build
project('demo', 'cpp', version: '1.0')

test(
    'demo-test',
    executable(
        'demo',
        [
            'demo.cpp',
        ],
        dependencies: [
            dependency('gtest'),
        ],
    ),
    protocol: 'gtest',
)
```

```sh
$ meson setup build -Db_coverage=true && ninja -C build/ test
(...)
$ ninja -C build/ coverage
(...)
Processing (...)/build/demo.p/demo.cpp.gcno
geninfo: ERROR: mismatched end line for _ZN16Demo_Foobar_Test8TestBodyEv at (...)/demo.cpp:3: 3 -> 5
	(use "geninfo --ignore-errors mismatch ..." to bypass this error)
(...)
```

**Comment by henry2cox** [comment] 2023-10-16 09:50
You can also set the option in your system or personal lcovrc file:  see `man lcovrc`.

I don't know anything about the meson build system - but I'm pretty sure that it is not magical.
Somewhere - possibly very deeply buried - there is a configuration file which tells the framework how to invoke the coverage tool.  That can be extended (e.g., to support configuration options which you pass in) or hacked (e.g., to pass specific options you think you need, today).
