### ISSUE TITLE
genhtml: ERROR: Can't call method "branchElem" on an undefined value

### ISSUE THREAD

**Issue by icsfy** [linux-test-project/lcov#293] opened 2024-05-20 03:38 UTC
Lcov 2.1, use `genhtml --branch --keep-going` to generate differential coverage, failed with these output:
```
genhtml: ERROR: (unmapped) no data for line:279, TLA:ECB, file:somefile.c
	(use "genhtml --ignore-errors unmapped ..." to bypass this error)
genhtml: ERROR: (unmapped) no data for line:281, TLA:EUB, file:somefile.c
genhtml: ERROR: (unmapped) no data for line:283, TLA:ECB, file:somefile.c
genhtml: ERROR: Can't call method "branchElem" on an undefined value
```
If --parallel is enabled, genhtml seems hangs at above error and not terminated.
I checked that `somefile.c`, it only contains 276 lines.
gcc version 9.4.0

**Comment by henry2cox** [comment] 2024-05-20 11:36
Thanks for the report.
I believe this is already fixed in my TOT - so I will push the update shortly.

Note that the root cause is related to data inconsistency:  the baseline, current, and source diff data do not agree with each other.
In our case, the issue was that the file paths in the 'diff' file did not match the names in the coverage data; the tool requires that path names be _identical_ (however, see the `genhtml --elide-path-mismatch ..` documentation for a workaround).
The bug fix simply removes the call to the undef object (so no crash) - but you will still see the `unmapped` error.
The fix also adds some additional text to the output logs, to make it easier to diagnose the cause of the mismatch.

The out-of-range line number issue is commonly caused by one or more of: 

 - inconsistent baseline/current/diff names - so the tool gets confused about the size of some file
 - version mismatches such that genhtml is not looking at the same source code as the data had been generated.
 Depending on your project and use model, it can be a good idea to use the `--version-script` lcov/genhml option to avoid inconsistencies caused by version differences.
 - bug in gcc/gcov/llvm/etc such that out-of-range lines appear in the output data.
 This is very common in lex/yacc/tablegen output - but also happens in other files.
 In those 'other files', the most common case is that gcov (or llvm-cov) report line _N+1_ in a file containing _N_ lines.
 See the `genhtml --synthesize-missing..`, `genhtml --filter range...` and `genhtml --ignore range...` options for possible workarounds.

**Closed** 2024-05-22 04:36 UTC
