### ISSUE TITLE
Exclude functions from code coverage

### ISSUE THREAD

**Issue by laksru** [linux-test-project/lcov#116] opened 2021-02-22 22:28 UTC
Hi,

It is good that we can exclude a line using lcov_excl_line and regex patterns in the config file. 
I am looking for a way to exclude a whole function in a file from code coverage using lcovrc where we can provide a list of functions that can be excluded. Please suggest.

**Comment by henry2cox** [comment] 2021-02-23 10:59
I’m curious what your application is – what are you trying to accomplish?
There may be another way, apart from exclusions.

Worst case – you can write a small filter to remove the data you don’t want to see from the .info file.  (File is ASCII – so this is not hard.)

Henry

**Comment by laksru** [comment] 2021-02-23 17:07
Hi Henry,

Thanks for your response. 
In our code base, we have our internal code and community code. We want to exclude the files and functions from the community code which is untouched, from the code coverage. The main reason for this ask is to optimize the code coverage results.
We are looking to combine file based, function based and line based filters to get a better code coverage of a feature.
I tried writing a filter script to exclude few lines of code but as we have 1000s of files with many lines of code, I felt it is ideal to have the list of functions to include that each developer can write and parse it to a config file to filter from code coverage (Not sure if it is possible).
Any ideas or help would be much appreciated. :)

**Comment by henry2cox** [comment] 2021-02-24 12:10
I guess the obvious question is why you can’t just exclude those files/directories which contain 3rd party or uninteresting code?  (“lcov –remove …”) – or why you can’t mark them as “external” (and thus excluded if you use the “--no-external” flag).
This is pretty much what we do internally, for a couple of our projects.

Is it the case that you make some changes in the 3rd party files and thus want to track parts of those files but not others?
If this is the case…then I would consider to make a couple of changes to your build flow – so your changes can be kept physically separated (and thus easy to NOT exclude).

Yet another possibility is to use my differential coverage tool ☺
The basic idea is that we care more about new code and/or recent code changes than we do about legacy code or 3rd party libraries.  Thus, we combine file history (from our revision control system) with historical coverage data (from our regression/continuous integration system) to categorize code into various buckets.  Our regression tool then watches the buckets we care about to tell us when something happens that we don’t like.  For example, our ‘coverage ratchet’ will trigger if someone checks in new code which is not covered, or checks in code which causes some other ‘old code’ to no longer be covered.
You can define what you mean by “new code” – for example, “new since the last release” or “since the previous successful build” – or whatever.
There are a couple of papers which describe the methodology, if you are interested.  There is also an open pull request, to integrate my changes.

Hope this helps.

Henry

**Comment by laksru** [comment] 2021-03-25 23:24
Sorry for my late response and Thanks a lot for your suggestions.

We make some changes in the 3rd party files where few functions are left untouched.

The coverage.py tool for Python has an advanced exclusion where we can mention the function names that needs to be excluded from code coverage with an annotation "pragma: no cover" in .coveragerc file. 
Ref: https://coverage.readthedocs.io/en/coverage-5.5/excluding.html#advanced-exclusion 
Is there any way in lcov tool to add function names in .lcovrc to exclude those functions from code coverage?

Also can you please give more details about the differential coverage tool. I would really like to go through the papers to understand the methodology.

Thanks again for responding.

**Comment by henry2cox** [comment] 2021-03-26 11:01
The pull request for my differential changes is #86 (though I added or changed quite a bit since it was originally created).
You can find the latest version I pushed at https://github.com/henry2cox/lcov/tree/diffcov_initial.  The readme points to an arxiv paper about the approach.  An updated/expanded version of that paper will be presented at an upcoming software test conference (virtual, next month I think).
With respect to the feature that you want - does this capture the requirement:
  - external file to specify exclusions
  - function exclusions specified with regexp
  - if function name matches regexp, then exclude the function itself and all lines and branches it contains, from the coverage report.
  - I guess you would also want to be able to specify a filename regexp (to exclude everything in that file) as well
  - I don't think it is a good idea to support file extents (line range exclusion directive) - because external files fall out-of-date wrt the source code WAY too easily - creating misleading results.

The only slightly tricky thing is that the lcov format doesn't store the function extent at present (only the start - not the end).  A bigger problem is that any such feature is easily defeated by a bloody-minded user who puts a #include in the function body.
Also - we are probably not the only ones who use lcov on languages other than C/C++ that support nested functions.  If a child is excluded without its parent, then the parent extent will be disjoint - which may be hard to handle.

I guess that another way to handle this would be with "include" pragmas (as opposed to the current 'exclude' pragmas).  They aren't external (...but you could write some filters to use your directives to generate the pragmas...) - but they also do not fall out of date WRT the code.

I think that the differential approach (possibly using ownership filters) will do very close to what you want.
(Modify your 'annotate' script to set everyone not in your organization to "External".)

Herny

**Comment by laksru** [comment] 2021-04-01 19:06
Hi Henry,

Thanks a lot for the valuable response. 
As you mentioned, These below points meet the requirements.
- external file to specify exclusions
- function exclusions specified with regexp
- if function name matches regexp, then exclude the function itself and all lines and branches it contains, from the coverage report.
- I guess you would also want to be able to specify a filename regexp (to exclude everything in that file) as well

Also as you said, line range based exclusions are not feasible because of the rapid changes in the files and difficult to maintain.

Coming to the Differential coverage tool, Thank you for implementing this tool. I have gone through the paper and would really like to try this. Can you please provide me the steps to generate a differential report for a simple c file, (I looked into the /tests/gendiffcov/ scripts).
Please consider me as a newbie :) 

Thanks in advance,
Lakshmi

**Comment by henry2cox** [comment] 2021-04-01 19:43
The basic steps are at the top of the file …/tests/gendiffcov/simple/script.sh:

1.       Compile and run your testcase, generating coverage data:

·       git branch baselineBranch  # I’m assuming your baseline version is in git somewhere..
gcc --coverage myFile.c  # compile baseline
./a.out # run

2.       collect the baseline coverage .info file:

·       lcov --capture --directory . --output-file baseline.info

3.       compile and run your testcase ‘current’ version:

·       git branch master  # assuming your current version is in master
gcc --coverage myFile.c # compile current version
./a.out # and run it

4.       collect the current coverage .info file:

·       lcov --capture --directory . --output-file current.info

5.       ask git for the ‘universal diff’ (or generate the diff file some other way)

·       git diff baselineBranch..master – myFile.c > udiff.txt

6.       run genhtml to produce the report:

·       genhtml --baseline-file ./baseline.info --diff-file udiff.txt --annotate-script `which gitblame` -o differential_report ./current.info  # this assumes that you put the ‘gitblame’ script into your path

If you don’t want date/owner binning or annotations, you don’t need the annotate script.
If you want annotations but not differential categorization:  don’t specify the baseline file.
If you want the traditional lcov reports (no differential categorization, no annotation):  don’t specify either the baseline or the annotation script.

The first issue you are likely to see (in any realistic, non-trivial project whose build is even moderately complex) – is that the paths in the .info file (generated by lcov) and the ‘diff’ file (from git, perforce – or however you chose to create it) – are not the same.
For example:  one of your tools might write full paths and the other relative.
The diffcov scripts are not so smart…they know that the ‘info’ file, the ‘diff’ file, and the annotations are referring to the same thing because the paths found in those files are _identical_.  If the paths are not identical – then the script will try to guess (but may fail to match, or may guess wrong).  If that happens, the easiest workaround is to use ‘sed’ to edit the various files so that the paths _do_ match.
This is also true of the ‘annotate’ script.  The provided ‘gitblame’ and ‘p4annotate’ sample scripts assume that they can call git or p4 with the pathname found in the .info file to retrieve file history.  If that isn’t where the files actually are (…because your build environment creates a mirror, for example) – then the sample script will fail.  You will need to customize the scripts for your own purposes.

The testcase in ‘script.sh’ attempts to try all of that ☺
(But it fakes the ‘annotate’ call – in part, because I wanted to have stable dates in the reports.)
You can edit down the script so it contains just the essential part (like the above) – and run it to see what happens.

I hope this helps.

Henry

**Comment by henry2cox** [comment] 2023-01-06 15:38
SHA 10c6ea06ef0a6 adds a '--erase-functions regexp' option to lcov/geninfo/genhtml.
This may implement your original request.  
Note that you have to use a reasonably recent toolchain  for the feature to work - e.g., gcc/9 or newer

Please see the man pages for details.

If this resolves the problem:  please close this issue.  Otherwise, please update to describe the remaining problems.
Thanks
Henry

**Comment by henry2cox** [comment] 2023-05-11 13:38
No updates to this issue in a very long time.
I believe that the issue is resolved/the requested functionality has been implemented.
Thus, I am closing this issue now.

If there is still a problem, please reopen this issue or file a new one.  Please include a detailed description of the problem and if possible, include a testcase which exhibits the issue.

I am trying to clean up the list of open issues to make it easier to find problems that still need to be addressed.
Herny

**Closed by henry2cox** 2023-05-11 13:38 UTC
