### ISSUE TITLE
why there is no lineCounts of each function when i get the .info files? 

### ISSUE THREAD

**Issue by JingnanJia** [linux-test-project/lcov#136] opened 2021-12-11 11:20 UTC
the results of .info like:
====
FN:3,_Z3onev
FNDA:10,_Z3onev
FN:5,_GLOBAL__sub_I__Z3onev
FNDA:1,_GLOBAL__sub_I__Z3onev

......
====

**Comment by henry2cox** [comment] 2021-12-11 11:24
What does the corresponding source code look like?
Which versions of what toochain are you using?
What was your compile and link line?
What OS and version are you on?

**Comment by JingnanJia** [comment] 2021-12-11 11:38
thanks. I mean that the lcov codes can generate " <start_line>,<end_line>,<count>, <name>" of functions, but my .info file doesn‘t include the "<end_line>,<count>" of functions, just <start_line> and <name>.

**Comment by JingnanJia** [comment] 2021-12-11 11:41
> What does the corresponding source code look like? Which versions of what toochain are you using? What was your compile and link line? What OS and version are you on?

thanks. I mean that the lcov codes can generate " <start_line>,<end_line> ,<count> ,<name>, " of functions, but my .info file doesn‘t include the "<end_line>,<count>" of functions, just <start_line> and <name>.

**Comment by henry2cox** [comment] 2021-12-11 11:48
I need to take a closer look at the code – but I think that currently, the .info file holds only the start line – and does not record the end line for functions.

It would either be fairly easy – or really not easy – to enhance lcov to do that.
Easy – because the data is more-or-less available.
Really not easy because the simple implementation would make the assumption that the function was contiguous and contained – and neither are true in general.

-          What do you do about lambdas?  They break up the range of the parent.

-          What do you do about bloody-minded users who like #include – and who break functions across multiple files, with start and end in different directories….

I think a better place to start is to ask “why do you want this?”  What is your application?  What are you trying to be able to do?

Henry

**Comment by JingnanJia** [comment] 2021-12-11 11:53
> I need to take a closer look at the code – but I think that currently, the .info file holds only the start line – and does not record the end line for functions. It would either be fairly easy – or really not easy – to enhance lcov to do that. Easy – because the data is more-or-less available. Really not easy because the simple implementation would make the assumption that the function was contiguous and contained – and neither are true in general. - What do you do about lambdas? They break up the range of the parent. - What do you do about bloody-minded users who like #include – and who break functions across multiple files, with start and end in different directories…. I think a better place to start is to ask “why do you want this?” What is your application? What are you trying to be able to do? Henry

thanks very much. i got it.

**Comment by JingnanJia** [comment] 2021-12-11 15:53
Excuse me, I have another question, can lcov count the effective lines of code for each function?

**Comment by JingnanJia** [comment] 2021-12-11 16:28
Because I want to get the end_line of each function, but obviously it can't be analyzed according to your previous explanation. 
But I saw that gcov's "--function-summary" can give the effective number of lines for each function, so that maybe we can get the end_line of each function based on the start_line and the effective number of lines.
So, for further work, now i want to know lcov of your work can give the effective number of lines for each function too?

**Comment by henry2cox** [comment] 2021-12-11 19:57
Merely knowing the number of lines in the function isn’t going to help, I fear.
Consider comments or #ifdef regions….they count as source lines, but aren’t counted by the compiler.
Similarly – statements which fall across multiple lines will also confuse your location tracking.

I still don’t understand what your ultimate application is.  Why do you need to know the last line?
What are you going to do with the information?
(If you do find a good way to do this – then I have an application for it as well – so I’m hopeful that there is a reasonably robust solution.)

You also appear to be assuming C/C++ - but lcov is useful for other languages too.

**Comment by xaizek** [comment] 2021-12-12 11:02
`gcov --json-format` provides ranges for functions (this is from `man gcov`):
```
           Each function has the following form:

                   {
                     "blocks": <blocks>,
                     "blocks_executed": <blocks_executed>,
                     "demangled_name": "<demangled_name>,
                     "end_column": <end_column>,
                     "end_line": <end_line>,
                     "execution_count": <execution_count>,
                     "name": <name>,
                     "start_column": <start_column>
                     "start_line": <start_line>
                   }
```
Older `--intermediate` format can provide end line of each function as well (older versions of GCC don't have it). `lcov` seems to always ignore this information (search `geninfo` for `start_line` to see where it's being processed).

**Comment by henry2cox** [comment] 2021-12-13 11:01
I had another kind of obvious thought yesterday:

-          I’m happy to write off bloody-minded users:  if you write pathological code with #includes all over the place…you should not be surprised if your tools are not happy.
I have regression tests that do this (for various reasons which seemed good at the time) – but no production code, AFAIK.

-          Lambdas are important, though.

If we were trying to find all the code lines in a particular function, then we should be able to use xaizek’s suggestion to find end lines – but we also need to check for (and exclude) functions which start within the range of some other function….those must be lambdas or nested functions (e.g., python) – which have their own range.

I don’t think that it is entirely trivial to make this all work completely, correctly, and consistently…but I’m going to take a look.
I think there is some useful information to be extracted, and some features that this cound enable.

Henry

**Comment by henry2cox** [comment] 2023-01-06 15:52
SHA 10c6ea06ef0a contains support for function start/end line reporting - but does require gcc/9 or newer.
I use it both to support exclusions ("remove <matching function> and all coverpoints it contains") and reporting ("show proportion of line/branch coverpoints contained in this function which are hit").
See the man page for details:  --erase-functions and --show-proportion flags.

If this meets your requirement:  please close this issue.
If something is broken or missing:  please describe the remaining problems...maybe we can fix them.

Thanks
Henry

**Comment by henry2cox** [comment] 2023-05-16 11:18
I think that the issues discussed here are addressed and merged to TOT.
Please see:

- 10c6ea06ef0a - which implements function exclusions as well as `--show-proprtion`
- 2bfaf3da897bd8 - which implement function end line derivation for older gcc/gcov versions which do not report it.

Given that the issues are fixed - I will close this issue in a week or two unless someone reports some additional problem.
In the meantime:  @JingnanJia may want to close this (or append additional information).

Henry

**Comment by henry2cox** [comment] 2023-05-24 10:22
Closing issue now.

If there is still a problem:  please either reopen this issue or file a new one.
Please include a detailed description of the problem, and also include a testcase which exhibits the issue, if at all possible.
Henry

**Closed by henry2cox** 2023-05-24 10:22 UTC
